name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      packages: read
      statuses: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: vinteo/multi-viewer
          # path: multi-viewer

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Persist npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - run: npm install

      - name: Build Website
        run: npm run build

      - name: Move assets
        run: mv ./build/client/assets ./build/client/multi-viewer

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/client/multi-viewer
